unstable_features = true
edition = "2018"
version = "Two"

comment_width = 120
format_code_in_doc_comments = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
max_width = 120
reorder_impl_items = true
